services:
  web:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    expose:
      - "80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    networks:
      - backend_proxy_net

networks:
  backend_proxy_net:
    driver: bridge
